#! /usr/bin/env python

import os
import glob

if not os.path.exists('chess-openings'):
	print('Please download chess-openings directory from "https://github.com/lichess-org/chess-openings"')
	exit(1)

fname = 'openings.eco'
eco_file = open(fname, 'w')

header = """\
# openings.eco
#
# Generated by Sam Kravitz
#
# This file contains a database of ECO codes for chess openings, for use with the. Scid chess database program.
#
# This file was generated using data from Lichess.org's chess openings repository, using a script I wrote myself.
# See https://github.com/samkravitz/chess/scid_eco for more information
#
# Feel free to use this file free of charge for any reason.

"""

eco_file.write(header)

tsvs = sorted(glob.glob('chess-openings/*.tsv'))
last = tsvs[-1]
for tsv in tsvs:
	print(f'parsing openings in {tsv}')
	with open(tsv) as f:
		# skip first line of each file.
		# it is a header line
		for line in f.readlines()[1:]:
			# each entry formatted as eco\t name\t pgn\n
			eco, name, pgn = line.split('\t')
			eco_file.write(f'{eco} "{name}" {pgn.strip()} *\n')

	# do not write a trailing newline to the file
	if tsv != last:
		eco_file.write('\n')	

eco_file.close()
print(f'\nSucessfully wrote {fname}')
